"Creación de pruebas sobre la demo"
jojacomu/retor_3_automationTesting pull request #1
Opened 2023-08-15 17:08 UTC by jojacomu

Se crean archivos para las pruebas sobre sitio demo.

2023-08-15 18:43 UTC, DanielCalleCO requested changes

2023-08-15 18:43 UTC, DanielCalleCO commented on cypress/e2e/1-getting-started/todo.cy.js
Este archivo lo podés borrar JJ

2023-08-15 18:43 UTC, DanielCalleCO commented on cypress/e2e/2-advanced-examples/actions.cy.js
Lo mismo toda esta carpeta "2-advanced-examples" la podés borrar

2023-08-15 18:43 UTC, DanielCalleCO commented on cypress/e2e/test1_Check_Load_Cards.cy.js
> +describe("Filtro por precio", () => {
no crees un describe para cada test, los describe son básicamente conjunto de pruebas.. con eso puedes hacer solo un describe, y el before() te va a servir para todos... en ese caso te recomendaría beforeEach()

2023-08-15 18:43 UTC, DanielCalleCO commented on cypress/e2e/test1_Check_Load_Cards.cy.js
> +        cy.log("Fin prueba limpiar filtros");
Estos logs son informativos para ti, pero no son necesarios ni se envían como buena práctica al realizar una entrega para revisión. Son lo mismo que un console.log, te ayudan para desarollar pero no se envían...

2023-08-15 18:43 UTC, DanielCalleCO commented on cypress/fixtures/example.json
este lo puedes borrar también

2023-08-15 18:43 UTC, DanielCalleCO commented on cypress/support/commands.js
En este caso este lo puedes borrar también

2023-08-15 18:57 UTC, jojacomu commented on cypress/fixtures/example.json
Done

2023-08-15 18:57 UTC, jojacomu commented on cypress/e2e/test1_Check_Load_Cards.cy.js
> +        cy.log("Fin prueba limpiar filtros");
Done

2023-08-15 18:57 UTC, jojacomu commented on cypress/e2e/test1_Check_Load_Cards.cy.js
> +describe("Filtro por precio", () => {
Done

2023-08-15 18:57 UTC, jojacomu commented on cypress/e2e/2-advanced-examples/actions.cy.js
Done

2023-08-15 18:57 UTC, jojacomu commented on cypress/e2e/1-getting-started/todo.cy.js
Done

2023-08-15 22:54 UTC, jojacomu commented
Hola @DanielCalleCO ya actualicé el archivo que faltaba.

2023-08-16 02:22 UTC, DanielCalleCO requested changes
Muy bien JJ, terminaste! solo agrega lo que te pido y listo!

2023-08-16 02:22 UTC, DanielCalleCO commented on cypress/e2e/test1_Check_Load_Cards.cy.js
> +    it("Seleccionar botón clear", () => {
En esta prueba, como la página carga las 18 tarjetas desde el comienzo, agrega un paso adicional en donde pongas un filtro, como en la prueba anterior, verifique la cantidad necesaria de cards que deben aparecer, y luego de click en CLEAR y ahí si verifique las 18

2023-08-16 17:31 UTC, jojacomu commented on cypress/e2e/test1_Check_Load_Cards.cy.js
> +    it("Seleccionar botón clear", () => {
Observaciones implementadas. Gracias @DanielCalleCO  Shalom!

2023-08-16 18:50 UTC, DanielCalleCO approved these changes

2023-08-16 18:51 UTC, merged